// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gateway

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE155e73dDecodeGithubComMrtroianPayserviceInternalGateway(in *jlexer.Lexer, out *PaymentGateway) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "URL":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE155e73dEncodeGithubComMrtroianPayserviceInternalGateway(out *jwriter.Writer, in PaymentGateway) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"URL\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentGateway) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE155e73dEncodeGithubComMrtroianPayserviceInternalGateway(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentGateway) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE155e73dEncodeGithubComMrtroianPayserviceInternalGateway(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentGateway) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE155e73dDecodeGithubComMrtroianPayserviceInternalGateway(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentGateway) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE155e73dDecodeGithubComMrtroianPayserviceInternalGateway(l, v)
}
func easyjsonE155e73dDecodeGithubComMrtroianPayserviceInternalGateway1(in *jlexer.Lexer, out *GatewayManager) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE155e73dEncodeGithubComMrtroianPayserviceInternalGateway1(out *jwriter.Writer, in GatewayManager) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GatewayManager) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE155e73dEncodeGithubComMrtroianPayserviceInternalGateway1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GatewayManager) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE155e73dEncodeGithubComMrtroianPayserviceInternalGateway1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GatewayManager) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE155e73dDecodeGithubComMrtroianPayserviceInternalGateway1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GatewayManager) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE155e73dDecodeGithubComMrtroianPayserviceInternalGateway1(l, v)
}
